pro1 = ('papel', 230, 1.99)
pro2 = ('caneta', 330, 2.99)
pro3 = ('caderno', 310, 15.00)
pro4 = ('lápis', 300, 1.00)

print("Detalhes do produto 1:")
print("produto:", pro1[0])
print("quantidade disponível: ", pro1[1])
print("preço unitário: ", pro1[2])
print()

print("Detalhes do produto 2:")
print("produto:", pro2[0])
print("quantidade disponível: :", pro2[1])
print("preço unitário: :", pro2[2])
print()

print("Detalhes do produto 3:")
print("produto:", pro3[0])
print("quantidade disponível: :", pro3[1])
print("preço unitário: :", pro3[2])
print()

print("Detalhes do produto 4:")
print("produto:", pro4[0])
print("quantidade disponível: :", pro4[1])
print("preço unitário: :", pro4[2])
print()